this commit contains task 3. GET /api/categories
Kristaps31/BE-Project-Games pull request #1
Opened 2023-02-20 16:47 UTC by Kristaps31

this commit contains task 3

2023-02-20 17:03 UTC, johnhutcheon commented on __tests__/app.test.js
> +        })
Rather than checking the first thing in the array, please iterate over the response to check each element in the array (hint- forEach would be useful!)

2023-02-20 17:05 UTC, johnhutcheon requested changes
Hi Kristaps, nice start! Please see my comments- if you could just amend the test please and resubmit when this is done. Nice work! 🙂

2023-02-21 10:18 UTC, Kristaps31 commented on __tests__/app.test.js
> +        })
Thanks for the suggestion, its a good point :)

2023-02-21 11:21 UTC, yalicee requested changes
Please write a 404 error handling test for this :)

2023-02-21 15:10 UTC, Kristaps31 commented
Amended as yalicee requested

2023-02-21 15:32 UTC, emilyb93 commented on __tests__/app.test.js
> +describe.only("GET /api/categories", () => {
remove .onlys

2023-02-21 15:41 UTC, emilyb93 approved these changes
remove the only and then this is good to go

2023-02-22 08:51 UTC, yalicee approved these changes
V happy with your work

2023-02-22 09:27 UTC, merged