4.get api reviews
Kristaps31/BE-Project-Games pull request #2
Opened 2023-02-21 12:10 UTC by Kristaps31

Please see completed task 4.

2023-02-21 13:43 UTC, Beth-McCormack commented on app.js
> +const app = experss();
check spelling of express

2023-02-21 13:45 UTC, Beth-McCormack commented on __tests__/app.test.js
> +    })
This is only testing first element in the array. Use iteration to check each element is what you'd expect.

2023-02-21 13:48 UTC, Beth-McCormack commented on __tests__/app.test.js
> +    })
can you add an expect statement here to check that the reviews are sorted in descending order as per the ticket description

2023-02-21 13:49 UTC, Beth-McCormack commented on __tests__/app.test.js
> +    })
This is only testing first element in the array. Use iteration to check each element is what you'd expect.

2023-02-21 13:52 UTC, Beth-McCormack requested changes
see comments

2023-02-22 09:40 UTC, johnhutcheon approved these changes
As per our slack conversation, I'll approve this, but just look at using Jest Sort in future to make things easier!

2023-02-22 09:59 UTC, merged