5.get api reviews review
Kristaps31/BE-Project-Games pull request #3
Opened 2023-02-22 10:31 UTC by Kristaps31

Please review this code,

It contains one test for valid, and one test for invalid input

2023-02-22 10:44 UTC, Beth-McCormack commented on __tests__/app.test.js
> +        .expect(400)
would this be a 400?

2023-02-22 10:45 UTC, Beth-McCormack commented on __tests__/app.test.js
> +    })
can you add a test for invalid id eg api/reviews/banana

2023-02-22 10:47 UTC, Beth-McCormack requested changes
see comment

2023-02-23 10:54 UTC, yalicee approved these changes
Great code!!! Keep it up

2023-02-23 12:41 UTC, merged